server:
  port: 8081
spring:
  security:
    filter:
      dispatch-options-request: true
    headers:
      content-security-policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"

  iotdb:
     username : root
     password: root
      ip：192.16.0.100
#    ip: 192.16.0.8
     port: 6667
     maxSize: 100
     predict_device:  root.ciia.fcg.unit1.preresult
     economic_device: root.ciia.fcg.unit1.economic
#    predict_device2: root.ciia.fcg.unit2.preresult
     predict_device2: root.vib
     JKD_Data: root.vib.pro
     economic_device2: root.ciia.fcg.unit2.economic

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.1.104:3306/snp_ciia?useUnicode=true&characterEncoding=utf-8&useSSL=false
##    url: jdbc:mysql://192.168.0.111:3306/snp_ciia?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: snp_ciia
#    password: Ciia#2203*0117

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.16.0.100:3306/anqing?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shiyanshi?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root


